### ISSUE TITLE
[Feature]: check TOML formatting

### ISSUE THREAD

**Issue by no30bit** [input-output-hk/catalyst-ci#404]
### Feature Title

New CI check for TOML files

### Feature Description

# Summary 

TOML files are currently arbitrarily formatted. This is not good for git diff and specifically for _Cargo.toml_ consistency. For example, a snippet from Hermes [_Cargo.toml_](https://github.com/input-output-hk/hermes/blob/b9876ea25dba3cc6c58ef54c6240da8d9906d0fb/hermes/bin/Cargo.toml):  

```toml
tokio = { version = "1.45.1", features = ["macros", "sync", "rt-multi-thread", "rt", "net"] } # Good formatting
libsqlite3-sys = {version="0.34.0", features = ["bundled"] } # Bad formatting
```

An extra CI check validating TOML files would be nice.

# Description

Validating TOML files can be done with [Taplo](https://taplo.tamasfe.dev) tool. It's available through `cargo install`, NPM, as a binary, etc. Precise formatting rules can be controlled with _taplo.toml_ file.

## CI install & check

In _catalyst-ci/earthly/rust/tools/Earthfile_ add:

```earthly
tool-taplo-cli:
    DO +CARGO_BINSTALL --package=taplo-cli --version=0.14.0
```

Then run it from _catalyst-ci/earthly/rust/scripts/std_checks.py_.

## Configuration example

As one of the features, dependencies in _Cargo.toml_ can be forced to be lexicographically ordered:

```toml
[formatting]
reorder_keys = false

[[rule]]
include = ["**/Cargo.toml"]
keys = ["dependencies"]

[rule.formatting]
reorder_keys = true
```

## Note

Depending on the chosen configuration, some of the TOML files would need to be re-formatted. 

### Use Case

GitHub action failure on bad TOML formatting.

### Is this a modification to an existing feature?

No
